name: Move Issue
on:
  issues:
    types:
      - milestoned

jobs:
  moveIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        id: env
        run: |
          echo "ISSUE_ID=${{ github.event.issue.node_id }}" >> $GITHUB_ENV
          echo "TARGET_PROJECT_ID=${{ secrets.TARGET_PROJECT_ID }}" >> $GITHUB_ENV
          echo "MILESTONE_TITLE=${{ github.event.issue.milestone.title }}" >> $GITHUB_ENV

      - name: Move Issue
        run: node move-issue.js
        env:
          GITHUB_TOKEN: ${{ secrets.MOVE_ISSUE_TOKEN }} # Required for repository access
