name: Move Issue to Another Project
on:
  issues:
    types: [milestoned]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run JavaScript file
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node move-issue.js
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}

