name: Move Issue to Another Project
on:
  issues:
    types: [milestoned]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ../move-issue.js
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run JavaScript file
        run: |
          npm install
          node move-issue.js
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}


